import type uPlot from 'uplot';
import { indexAt, modeOf, type Problem, type Span, type Stats } from './analysis';
import type { DSEvent } from './dsevents';
import { FLAG, ROBOT_MODE_MASK, type DSLog } from './dslog';
import { channelName } from './settings';
import { fmtDuration, fmtSpan } from './time';

export function download(data: BlobPart, filename: string, type = 'text/plain') {
  const blob = data instanceof Blob ? data : new Blob([data], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

const csvCell = (v: string | number) => {
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

const num = (v: number, d = 3) => (Number.isNaN(v) ? '' : Number(v.toFixed(d)));

export function logToCsv(log: DSLog, range: Span, labels?: string[], matchStart?: number): string {
  const i0 = indexAt(log, range.start);
  const i1 = indexAt(log, range.end);
  const header = [
    'time_s',
    'match_time_s',
    'clock',
    'ds_mode',
    'robot_connected',
    'robot_code_reporting',
    'brownout',
    'watchdog',
    'battery_v',
    'trip_ms',
    'packet_loss_pct',
    'rio_cpu_pct',
    'can_util_pct',
    'wifi_db',
    'wifi_mb',
    'total_current_a',
    ...log.currents.map((_, ch) => `${channelName(labels, ch)} (A)`),
  ];
  const rows = [header.map(csvCell).join(',')];
  for (let i = i0; i <= i1; i++) {
    const f = log.flags[i];
    const t = i * log.period;
    rows.push(
      [
        num(t, 2),
        matchStart != null ? num(t - matchStart, 2) : '',
        new Date((log.startTime + t) * 1000).toISOString(),
        modeOf(f),
        log.comms[i],
        log.comms[i] && f & ROBOT_MODE_MASK ? 1 : 0,
        f & FLAG.BROWNOUT ? 1 : 0,
        f & FLAG.WATCHDOG ? 1 : 0,
        num(log.voltage[i]),
        num(log.tripMs[i], 1),
        num(log.packetLoss[i], 1),
        num(log.cpu[i], 1),
        num(log.can[i], 1),
        num(log.wifiDb[i], 1),
        num(log.wifiMb[i], 2),
        num(log.totalCurrent[i], 2),
        ...log.currents.map((c) => num(c[i], 3)),
      ].join(','),
    );
  }
  return rows.join('\n');
}

export function eventsToCsv(events: DSEvent[], matchStart?: number): string {
  const rows = [['time_s', 'match_time_s', 'kind', 'code', 'robot_time_s', 'message', 'location'].join(',')];
  for (const e of events)
    rows.push(
      [
        num(e.t, 3),
        matchStart != null ? num(e.t - matchStart, 3) : '',
        e.kind,
        e.code ?? '',
        e.robotTime ?? '',
        csvCell(e.text),
        csvCell(e.location ?? ''),
      ].join(','),
    );
  return rows.join('\n');
}

export function summaryMarkdown(opts: {
  title: string;
  subtitle: string;
  stats: Stats;
  problems: Problem[];
}): string {
  const { title, subtitle, stats: s, problems } = opts;
  const icon = { bad: '🔴', warn: '🟡', info: '🔵' } as const;
  const lines = [
    `**${title}** — ${subtitle}`,
    '',
    `Battery: min ${s.voltage.min.toFixed(2)} V, resting ${Number.isNaN(s.voltage.resting) ? '–' : s.voltage.resting.toFixed(2) + ' V'} · Brownouts: ${s.brownouts.count}`,
    `Comms: ${s.comms.enabledDrops} drops while enabled · trip avg ${s.trip.avg.toFixed(1)} ms · loss avg ${s.loss.avg.toFixed(1)}%`,
    `roboRIO: CPU avg ${s.cpu.avg.toFixed(0)}% · CAN max ${s.can.max.toFixed(0)}%` +
      (s.current.available ? ` · Peak current ${s.current.peak.toFixed(0)} A · Used ${s.current.ah.toFixed(2)} Ah` : ''),
    `Enabled ${fmtSpan(s.enabledTime)} (auto ${fmtSpan(s.autoTime)}, teleop ${fmtSpan(s.teleopTime)})`,
    '',
    problems.length ? '**Findings**' : '**No problems found** ✅',
    ...problems.map((p) => `${icon[p.severity]} ${p.title} — ${p.detail}${p.fix ? ` **Check:** ${p.fix}` : ''}`),
    '',
    `_Generated by PitView · scope ${fmtDuration(s.span.start, 0)}–${fmtDuration(s.span.end, 0)}_`,
  ];
  return lines.join('\n');
}

/** Stacks the canvases of the given charts into one PNG with a title. */
export async function chartsToPng(plots: uPlot[], title: string, background: string, text: string): Promise<Blob> {
  const dpr = devicePixelRatio || 1;
  const pad = 16 * dpr;
  const titleH = 36 * dpr;
  const canvases = plots.map((u) => u.ctx.canvas);
  const width = Math.max(...canvases.map((c) => c.width), 400) + pad * 2;
  const height = canvases.reduce((a, c) => a + c.height + pad, titleH + pad);
  const out = document.createElement('canvas');
  out.width = width;
  out.height = height;
  const ctx = out.getContext('2d')!;
  ctx.fillStyle = background;
  ctx.fillRect(0, 0, width, height);
  ctx.fillStyle = text;
  ctx.font = `600 ${16 * dpr}px system-ui, sans-serif`;
  ctx.fillText(title, pad, pad + 16 * dpr);
  let y = titleH + pad;
  for (const c of canvases) {
    ctx.drawImage(c, pad, y);
    y += c.height + pad;
  }
  return new Promise((resolve, reject) => out.toBlob((b) => (b ? resolve(b) : reject(new Error('PNG export failed'))), 'image/png'));
}

export function safeFileName(s: string): string {
  return s.replace(/[\\/:*?"<>|]+/g, '-').replace(/\s+/g, ' ').trim();
}
